### PR TITLE
Move ProjectSettings/AndroidLogcatSettings.asset to UserSettings/AndroidLogcatSettings.asset

### PR DESCRIPTION
**Pull request by todi1856**
### Purpose of PR
**Type of change:**
- [X] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other (please describe) 

* **Description of the feature**
ProjectSettings is a folder meant to be commited to source control, but there's nothing in ProjectSettings/AndroidLogcatSettings.asset what should be commited, thus I moved it to UserSettings/AndroidLogcatSettings.asset

Here's what AndroidLogcatSettings.asset contains
```
{
    "m_SelectedDeviceId": "",
    "m_SelectedPackage": {
        "deviceId": "",
        "name": "",
        "processId": 0,
        "exited": false
    },
    "m_SelectedPriority": 0,
    "m_KnownPackagesForSerialization": [],
    "m_Tags": {
        "m_Entries": [
            {
                "m_Name": "Filter by all listed tags",
                "m_Selected": false
            },
            {
                "m_Name": "No Filter",
                "m_Selected": true
            },
            {
                "m_Name": "",
                "m_Selected": false
            },
            {
                "m_Name": "Tag Control...",
                "m_Selected": false
            },
            {
                "m_Name": "",
                "m_Selected": false
            },
            {
                "m_Name": "Unity",
                "m_Selected": false
            },
            {
                "m_Name": "CRASH",
                "m_Selected": false
            }
        ]
    },
    "m_MemoryViewerState": {
        "MemoryWindowHeight": 300.0,
        "MemoryWindowWidth": 170.0,
        "MemoryTypeEnabled": [
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true
        ],
        "MemoryGroup": 2,
        "Behavior": 1
    },
    "m_Filter": "",
    "m_FilterIsRegularExpression": false,
    "m_SymbolPaths": []
}
```
You might argue that Tags could be consider a project specific setting, but since they're bundled with selected property, it doesn't make to have them in project settings, since selecting a tag would be reflected on other users machine using the same project which would unexpected.

* **Links to screenshots, design docs, user docs, etc.**
* **Links to Jira/Fogbugz cases**
https://github.com/Unity-Technologies/com.unity.mobile.logcat/issues/117
* **Halo effect**
None
* **Performance Impact**
None
* **Package requirements**
Nothing changed with requirements

### Checklist for PR maker
- [ ] Have you added a backport label? (if needed)
- [X] Have you updated the Changelog? _Each package has a `CHANGELOG.md` file_
- [ ] **Have you added or updated the Documentation to your PR?** 
No
---
### Testing status
* **Existing or new automation tests - what automation was added, changed**
The existing tests were updated
* **Detailed description of what testing was done, what projects were run**
Manually validated that after closing Editor, Android Logcat saves setttings to UserSettings instead.
* **What environment did you test on?**
Windows
* **Projects**
Any project using logcat will do the trick, I used projects from inside the repo
* **Testing checklist**
- [ ] Built and run editor Locally or Katana
- [ ] Built a player Android/iOS (if applicable)
- [ ] Run on device Android/iOS (if applicable)
- [ ] If new feature has UI, does it match Unity style? (Unity [HIG](https://unitytech.github.io/unityeditor-hig/)?)
- [ ] Tested Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] All items have tooltips?
---
### Note to guardian
_Changeset to use, if extra changesets on top. Any other notes to pass along_

### Comments to reviewers
Just check, that Android settings are saved in UserSettings

### CODE REVIEW

**Comment by vincent-unity** [comment]
Before reviewing, I'm curious about where you got this fancy pr description template. 😄

**Comment by JuozasK** [comment]
> Before reviewing, I'm curious about where you got this fancy pr description template. 😄

It was an idea I had to push for a more standardized PR template for all packages, so testing would be easier. 
https://docs.google.com/document/d/1S5KZ9i5tOe35W2BbDfkncfdsxfqXu8juBbVtRUAEeJc/edit
Here's a short tutorial on how to add it to your repositories

**Review by JuozasK — APPROVED** [review]
Talked with Tomas, everything should work as before. If UserSettings directory doesn't exist, there's a catch for that too. Looks good to me.

**Review by vincent-unity — APPROVED** [review]

**Comment by Rabadash8820** [comment]
Thanks for the quick turnaround @todi1856 and @JuozasK! Any idea when we can expect this change in the deployed package?

**Comment by todi1856** [comment]
Not sure, maybe 2-3 weeks. The fastest way is to clone master branch, and then do Add From Disk from Package Manager.

**Comment by Rabadash8820** [comment]
Ah yes, always forget about adding from disk. Thanks again!

**Pull request merged**
